on:
  push:
  pull_request:
    branches:
    - master

jobs:
  E2E_Tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    strategy:
          matrix:
            node-version: [14.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm run test

      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: test-results/*
