name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  E2E_Tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    strategy:
          matrix:
            node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Playwright GitHub action
        uses: microsoft/playwright-github-action@v1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps
      
      - name: Run tests
        run: npm run test

      - name: Rename & zipped test results
        shell: bash
        if: ${{ always() }}
        run : |
          sh src/scripts/renameTestResults.sh
          sh src/scripts/zipTestResults.sh

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: test-results/*

      - name: Upload zipped test artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: test-results-zip/*

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-logs
          path: test-logs/*

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: E2E Test Report             # Name of the check run which will be created
          path: test-results/results.xml    # Path to test results
          reporter: jest-junit              # Format of test results
